---
extends: '@istanbuljs/nyc-config-babel'
report-dir: ./coverage
timeout: 6000
check-coverage: true
all: true
include:
  - index.js
  - src
exclude:
  - '**/*.spec.js'
  - '**/*.test.js'
  - '**/test/**/*.js'
reporter:
  - text
  - lcov
